version: "3"

services:
  node:
    build: .
    container_name: api
    user: node
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: db-api
      POSTGRES_HOST: db
      JWT_SECRET: secretJWT
      API_HOST: 'node'
      API_PORT: 3000
      DB_PORT: 5432
  db:
    image: 'postgres:latest'
    restart: always
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - '5432:5432'